version: '3'

services:
  mongo_db:
    image: mongo:latest
    container_name: calendar-mongo-db
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
    env_file:
    - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_PORT: ${MONGO_INITDB_PORT}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}